name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Login to Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Install Newman + Reporter
      - name: Install Newman + HTMLExtra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run API Tests with Newman + HTML Report
      - name: Run API tests and Generate HTML Report
        run: |
          newman run "https://api.getpostman.com/collections/47021590-396e8cf8-809a-48d3-be2b-2eee9e21794c?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            -r htmlextra \
            --reporter-htmlextra-export index.html

      # Upload HTML Report Artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-api-report
          path: index.html
